# This file was generated by GoReleaser. DO NOT EDIT.
cask "djot-fmt" do
  version "0.2.4"

  on_macos do
    on_arm do
      sha256 "c51627ab689cbbcb3db229915414870a026029b3831ab46739fa83ba800154a8"
      url "https://github.com/KyleKing/djot-fmt/releases/download/v#{version}/djot-fmt-darwin-arm64"
      binary "djot-fmt-darwin-arm64", target: "djot-fmt"
    end
    on_intel do
      sha256 "972080d51255032b85bb1ffff0629921ab349e61b302ec233204f89769200388"
      url "https://github.com/KyleKing/djot-fmt/releases/download/v#{version}/djot-fmt-darwin-amd64"
      binary "djot-fmt-darwin-amd64", target: "djot-fmt"
    end
  end
  on_linux do
    on_arm do
      sha256 "bf8f90410c6d83a649e15b1e78c67be96669143725a996a2920d09d5834af294"
      url "https://github.com/KyleKing/djot-fmt/releases/download/v#{version}/djot-fmt-linux-arm64"
      binary "djot-fmt-linux-arm64", target: "djot-fmt"
    end
    on_intel do
      sha256 "27df640ad63bf22b1c5a3cc5327eb2094fd96ca20a3086b4449d8eac4ee59b2c"
      url "https://github.com/KyleKing/djot-fmt/releases/download/v#{version}/djot-fmt-linux-amd64"
      binary "djot-fmt-linux-amd64", target: "djot-fmt"
    end
  end

  name "djot-fmt"
  desc "Automatic formatter for djot markup files"
  homepage "https://github.com/KyleKing/djot-fmt"

  livecheck do
    skip "Auto-generated on release."
  end

  postflight do
    Dir.glob(File.join(staged_path, "djot-fmt*")).each do |f|
      system_command "/usr/bin/xattr", args: ["-c", f], must_succeed: false
    end
  end

  # No zap stanza required
end
