# This file was generated by GoReleaser. DO NOT EDIT.
cask "djot-fmt" do
  version "0.2.3"

  on_macos do
    on_arm do
      sha256 "22871da01bc9d337fb2212e9a0fce4137dd30b57bea96f4b6a87497bae3c7bef"
      url "https://github.com/KyleKing/djot-fmt/releases/download/v#{version}/djot-fmt-darwin-arm64"
      binary "djot-fmt-darwin-arm64", target: "djot-fmt"
    end
    on_intel do
      sha256 "4161bfc2452d48334f60518d81110d5a123cbd213e297bf4f78b9174a3284c25"
      url "https://github.com/KyleKing/djot-fmt/releases/download/v#{version}/djot-fmt-darwin-amd64"
      binary "djot-fmt-darwin-amd64", target: "djot-fmt"
    end
  end
  on_linux do
    on_arm do
      sha256 "46540bd1e2a60db7962b2d34af780b4d264d3d1bd079dd8c66ccea01b141f157"
      url "https://github.com/KyleKing/djot-fmt/releases/download/v#{version}/djot-fmt-linux-arm64"
      binary "djot-fmt-linux-arm64", target: "djot-fmt"
    end
    on_intel do
      sha256 "5802cb5bcea0cdd47cf8d50d69497d27fc1db298ee8ce918b0ac90a52810b614"
      url "https://github.com/KyleKing/djot-fmt/releases/download/v#{version}/djot-fmt-linux-amd64"
      binary "djot-fmt-linux-amd64", target: "djot-fmt"
    end
  end

  name "djot-fmt"
  desc "Automatic formatter for djot markup files"
  homepage "https://github.com/KyleKing/djot-fmt"

  livecheck do
    skip "Auto-generated on release."
  end

  postflight do
    Dir.glob(File.join(staged_path, "djot-fmt*")).each do |f|
      system_command "/usr/bin/xattr", args: ["-c", f], must_succeed: false
    end
  end

  # No zap stanza required
end
