# This file was generated by GoReleaser. DO NOT EDIT.
cask "djot-fmt" do
  version "0.2.2"

  on_macos do
    on_arm do
      sha256 "55129d661508f61657bc761c1bb531428b1e183dbcc8aa1a90ca5113005f5009"
      url "https://github.com/KyleKing/djot-fmt/releases/download/v#{version}/djot-fmt-darwin-arm64"
      binary "djot-fmt-darwin-arm64", target: "djot-fmt"
    end
    on_intel do
      sha256 "d63c16ec2069e36327393a1669f761f6c5e87ebd7e62b872d3328f3eadbd0d42"
      url "https://github.com/KyleKing/djot-fmt/releases/download/v#{version}/djot-fmt-darwin-amd64"
      binary "djot-fmt-darwin-amd64", target: "djot-fmt"
    end
  end
  on_linux do
    on_arm do
      sha256 "c59a3745a365de9e360d4ce30beb9ea69bd103340e44501be462fd8e3ce3fb04"
      url "https://github.com/KyleKing/djot-fmt/releases/download/v#{version}/djot-fmt-linux-arm64"
      binary "djot-fmt-linux-arm64", target: "djot-fmt"
    end
    on_intel do
      sha256 "312613782e3d67d42ec05eb6764cda6ade2c8304e2cbc258e4d44ae2e7a41ebc"
      url "https://github.com/KyleKing/djot-fmt/releases/download/v#{version}/djot-fmt-linux-amd64"
      binary "djot-fmt-linux-amd64", target: "djot-fmt"
    end
  end

  name "djot-fmt"
  desc "Automatic formatter for djot markup files"
  homepage "https://github.com/KyleKing/djot-fmt"

  livecheck do
    skip "Auto-generated on release."
  end

  postflight do
    Dir.glob(File.join(staged_path, "djot-fmt*")).each do |f|
      system_command "/usr/bin/xattr", args: ["-c", f], must_succeed: false
    end
  end

  # No zap stanza required
end
