# This file was generated by GoReleaser. DO NOT EDIT.
cask "doneram" do
  version "0.2.0"

  on_macos do
    on_arm do
      sha256 "296f59d2455ff3387f13ca5a3d72a2e774fb41672163099f10c5a543aec3ac71"
      url "https://github.com/kyleking/doneram/releases/download/v#{version}/doneram-darwin-arm64"
      binary "doneram-darwin-arm64", target: "doneram"
    end
    on_intel do
      sha256 "9bf426137f2be4674eeb995dc499f4cd4b47d2238d7a3cba2149d5f8dbdebdde"
      url "https://github.com/kyleking/doneram/releases/download/v#{version}/doneram-darwin-amd64"
      binary "doneram-darwin-amd64", target: "doneram"
    end
  end
  on_linux do
    on_arm do
      sha256 "aa8ed78aee66c25595e4e16f312a1646f4fa51e759ed6ad8512cf60bd382f588"
      url "https://github.com/kyleking/doneram/releases/download/v#{version}/doneram-linux-arm64"
      binary "doneram-linux-arm64", target: "doneram"
    end
    on_intel do
      sha256 "4218bc4a4a1ad7c53870ee74a5e8eeb38c29737baa7d0b8d0286d14953eeacc1"
      url "https://github.com/kyleking/doneram/releases/download/v#{version}/doneram-linux-amd64"
      binary "doneram-linux-amd64", target: "doneram"
    end
  end

  name "doneram"
  desc "Keeps pinned versions current"
  homepage "https://github.com/kyleking/doneram"

  livecheck do
    skip "Auto-generated on release."
  end

  postflight do
    Dir.glob(File.join(staged_path, "doneram*")).each do |f|
      system_command "/usr/bin/xattr", args: ["-c", f], must_succeed: false
    end
  end

  # No zap stanza required
end
