# This file was generated by GoReleaser. DO NOT EDIT.
cask "doneram" do
  version "0.4.0"

  on_macos do
    on_arm do
      sha256 "bc75baa14530462f6be2d04f5dedb2dc99646f24ca1aa0ede7a4b7b175759485"
      url "https://github.com/kyleking/doneram/releases/download/v#{version}/doneram-darwin-arm64"
      binary "doneram-darwin-arm64", target: "doneram"
    end
    on_intel do
      sha256 "e286c52ba185c7bedc67147878684b31b95f33538be83f4dc8d9dc248a391e06"
      url "https://github.com/kyleking/doneram/releases/download/v#{version}/doneram-darwin-amd64"
      binary "doneram-darwin-amd64", target: "doneram"
    end
  end
  on_linux do
    on_arm do
      sha256 "3283cadbd9f1ecd0f53cdc59b52ac723f1d3d52eb545545971d29f726af5c239"
      url "https://github.com/kyleking/doneram/releases/download/v#{version}/doneram-linux-arm64"
      binary "doneram-linux-arm64", target: "doneram"
    end
    on_intel do
      sha256 "a7d69af221e1e35921c80efd503d20e228015e7bb4b2601f97245c163b43189c"
      url "https://github.com/kyleking/doneram/releases/download/v#{version}/doneram-linux-amd64"
      binary "doneram-linux-amd64", target: "doneram"
    end
  end

  name "doneram"
  desc "Keeps pinned versions current"
  homepage "https://github.com/kyleking/doneram"

  livecheck do
    skip "Auto-generated on release."
  end

  postflight do
    Dir.glob(File.join(staged_path, "doneram*")).each do |f|
      system_command "/usr/bin/xattr", args: ["-c", f], must_succeed: false
    end
  end

  # No zap stanza required
end
