# This file was generated by GoReleaser. DO NOT EDIT.
cask "doneram" do
  version "0.2.3"

  on_macos do
    on_arm do
      sha256 "248672387321b19f513ce88e13e9d0977bde5e0db93de5e574b5172092ffe444"
      url "https://github.com/kyleking/doneram/releases/download/v#{version}/doneram-darwin-arm64"
      binary "doneram-darwin-arm64", target: "doneram"
    end
    on_intel do
      sha256 "2c0c8c370db2d425d52ecfb50d796f0fd584556afe0515b4d30629b47c994770"
      url "https://github.com/kyleking/doneram/releases/download/v#{version}/doneram-darwin-amd64"
      binary "doneram-darwin-amd64", target: "doneram"
    end
  end
  on_linux do
    on_arm do
      sha256 "66e67a0f5a145031fe70ed530adcc62533c3148372cd64e5c9628643c7a0cd1a"
      url "https://github.com/kyleking/doneram/releases/download/v#{version}/doneram-linux-arm64"
      binary "doneram-linux-arm64", target: "doneram"
    end
    on_intel do
      sha256 "5aaf674bdba266a7e4b0550ce7b191966b978b35c693ee14e53e7506e03b4446"
      url "https://github.com/kyleking/doneram/releases/download/v#{version}/doneram-linux-amd64"
      binary "doneram-linux-amd64", target: "doneram"
    end
  end

  name "doneram"
  desc "Keeps pinned versions current"
  homepage "https://github.com/kyleking/doneram"

  livecheck do
    skip "Auto-generated on release."
  end

  postflight do
    Dir.glob(File.join(staged_path, "doneram*")).each do |f|
      system_command "/usr/bin/xattr", args: ["-c", f], must_succeed: false
    end
  end

  # No zap stanza required
end
