# This file was generated by GoReleaser. DO NOT EDIT.
cask "gh-lazydispatch" do
  version "1.4.0"

  on_macos do
    on_arm do
      sha256 "7dabd6c6b8430eef7cc363476330e17d25069cc6d0680bc019d482fc36e031ea"
      url "https://github.com/KyleKing/gh-lazydispatch/releases/download/v#{version}/gh-lazydispatch-darwin-arm64"
      binary "gh-lazydispatch-darwin-arm64", target: "gh-lazydispatch"
    end
    on_intel do
      sha256 "be739e2d47a9beb323e1cee2c87921c6940b434cb7a8272f41d87f770efd9853"
      url "https://github.com/KyleKing/gh-lazydispatch/releases/download/v#{version}/gh-lazydispatch-darwin-amd64"
      binary "gh-lazydispatch-darwin-amd64", target: "gh-lazydispatch"
    end
  end
  on_linux do
    on_arm do
      sha256 "c1a5c245e3994f13fc890502883da34b54b50e02d014376dabb7ea17d29ceca6"
      url "https://github.com/KyleKing/gh-lazydispatch/releases/download/v#{version}/gh-lazydispatch-linux-arm64"
      binary "gh-lazydispatch-linux-arm64", target: "gh-lazydispatch"
    end
    on_intel do
      sha256 "02890312eace30e59249b97156d0d43ca1f1ed1ad7ab6ff1487d8305781e8371"
      url "https://github.com/KyleKing/gh-lazydispatch/releases/download/v#{version}/gh-lazydispatch-linux-amd64"
      binary "gh-lazydispatch-linux-amd64", target: "gh-lazydispatch"
    end
  end

  name "gh-lazydispatch"
  desc "Interactive GitHub Workflow Dispatcher (standalone or with the GH CLI)"
  homepage "https://github.com/kyleking/gh-lazydispatch"

  livecheck do
    skip "Auto-generated on release."
  end

  postflight do
    Dir.glob(File.join(staged_path, "gh-lazydispatch*")).each do |f|
      system_command "/usr/bin/xattr", args: ["-c", f], must_succeed: false
    end
  end

  # No zap stanza required
end
