# This file was generated by GoReleaser. DO NOT EDIT.
cask "gh-lazydispatch" do
  version "1.5.0"

  on_macos do
    on_arm do
      sha256 "7a79e0d6d3bc2655f9f29a3ecee34ea1f77aea072630949291497252c811bcbf"
      url "https://github.com/KyleKing/gh-lazydispatch/releases/download/v#{version}/gh-lazydispatch-darwin-arm64"
      binary "gh-lazydispatch-darwin-arm64", target: "gh-lazydispatch"
    end
    on_intel do
      sha256 "1adc8273a59d90a9e5eb07675374134a08394d382b45a558fe5c7f05132bbd14"
      url "https://github.com/KyleKing/gh-lazydispatch/releases/download/v#{version}/gh-lazydispatch-darwin-amd64"
      binary "gh-lazydispatch-darwin-amd64", target: "gh-lazydispatch"
    end
  end
  on_linux do
    on_arm do
      sha256 "a254382618256a32a19cdef08a84468d29e1553455e44cb4a37817364cdcd709"
      url "https://github.com/KyleKing/gh-lazydispatch/releases/download/v#{version}/gh-lazydispatch-linux-arm64"
      binary "gh-lazydispatch-linux-arm64", target: "gh-lazydispatch"
    end
    on_intel do
      sha256 "ef3d12d4999ba5b571df6bc34315fa98bad779e04a04dad3a6e5c8f0bff31a45"
      url "https://github.com/KyleKing/gh-lazydispatch/releases/download/v#{version}/gh-lazydispatch-linux-amd64"
      binary "gh-lazydispatch-linux-amd64", target: "gh-lazydispatch"
    end
  end

  name "gh-lazydispatch"
  desc "Interactive GitHub Workflow Dispatcher (standalone or with the GH CLI)"
  homepage "https://github.com/kyleking/gh-lazydispatch"

  livecheck do
    skip "Auto-generated on release."
  end

  postflight do
    Dir.glob(File.join(staged_path, "gh-lazydispatch*")).each do |f|
      system_command "/usr/bin/xattr", args: ["-c", f], must_succeed: false
    end
  end

  # No zap stanza required
end
