# This file was generated by GoReleaser. DO NOT EDIT.
cask "gh-lazydispatch" do
  version "1.7.0"

  on_macos do
    on_arm do
      sha256 "cd14cd66be71d7450c5e7440dedce1fbe52ed2c81267351d51914139afd9647f"
      url "https://github.com/KyleKing/gh-lazydispatch/releases/download/v#{version}/gh-lazydispatch-darwin-arm64"
      binary "gh-lazydispatch-darwin-arm64", target: "gh-lazydispatch"
    end
    on_intel do
      sha256 "889ffe5e96778097f0c776a997ec62233ec2d6cb1221d9a3149472bc96bc6b1f"
      url "https://github.com/KyleKing/gh-lazydispatch/releases/download/v#{version}/gh-lazydispatch-darwin-amd64"
      binary "gh-lazydispatch-darwin-amd64", target: "gh-lazydispatch"
    end
  end
  on_linux do
    on_arm do
      sha256 "6fa944d5593f52026d9c2eee257de05978c601351467042ed796e58906b36669"
      url "https://github.com/KyleKing/gh-lazydispatch/releases/download/v#{version}/gh-lazydispatch-linux-arm64"
      binary "gh-lazydispatch-linux-arm64", target: "gh-lazydispatch"
    end
    on_intel do
      sha256 "25ca2b4615a2ac660260e325c3d18c4f0f9ae6d3df037c4609066c9bb156feda"
      url "https://github.com/KyleKing/gh-lazydispatch/releases/download/v#{version}/gh-lazydispatch-linux-amd64"
      binary "gh-lazydispatch-linux-amd64", target: "gh-lazydispatch"
    end
  end

  name "gh-lazydispatch"
  desc "Interactive GitHub Workflow Dispatcher (standalone or with the GH CLI)"
  homepage "https://github.com/kyleking/gh-lazydispatch"

  livecheck do
    skip "Auto-generated on release."
  end

  postflight do
    Dir.glob(File.join(staged_path, "gh-lazydispatch*")).each do |f|
      system_command "/usr/bin/xattr", args: ["-c", f], must_succeed: false
    end
  end

  # No zap stanza required
end
