# This file was generated by GoReleaser. DO NOT EDIT.
cask "gh-repo-dashboard" do
  version "1.10.2"

  on_macos do
    on_arm do
      sha256 "eee2bf708cd75a71ebfd53ee7afca0851d49dcbfcfb22e640cc8e0860c17d40a"
      url "https://github.com/KyleKing/gh-repo-dashboard/releases/download/v#{version}/gh-repo-dashboard-darwin-arm64"
      binary "gh-repo-dashboard-darwin-arm64", target: "gh-repo-dashboard"
    end
    on_intel do
      sha256 "9fbc0d5a6911581e7a6b58ac217f8a0e60bbbdf131cca9deebbf9848e0829557"
      url "https://github.com/KyleKing/gh-repo-dashboard/releases/download/v#{version}/gh-repo-dashboard-darwin-amd64"
      binary "gh-repo-dashboard-darwin-amd64", target: "gh-repo-dashboard"
    end
  end
  on_linux do
    on_arm do
      sha256 "46a8730e3c36ae3a4be1bdcb63b325245dfdc1afcafa57eb5f3cd4df3ffdfe68"
      url "https://github.com/KyleKing/gh-repo-dashboard/releases/download/v#{version}/gh-repo-dashboard-linux-arm64"
      binary "gh-repo-dashboard-linux-arm64", target: "gh-repo-dashboard"
    end
    on_intel do
      sha256 "5a0a6ab6d30edbf971aeb4eb6667dff8958effa6b418b1decf709fba3a0a5dec"
      url "https://github.com/KyleKing/gh-repo-dashboard/releases/download/v#{version}/gh-repo-dashboard-linux-amd64"
      binary "gh-repo-dashboard-linux-amd64", target: "gh-repo-dashboard"
    end
  end

  name "gh-repo-dashboard"
  desc "K9s-inspired Bubble Tea TUI for managing multiple git and jj repositories"
  homepage "https://github.com/kyleking/gh-repo-dashboard"

  livecheck do
    skip "Auto-generated on release."
  end

  postflight do
    Dir.glob(File.join(staged_path, "gh-repo-dashboard*")).each do |f|
      system_command "/usr/bin/xattr", args: ["-c", f], must_succeed: false
    end
  end

  # No zap stanza required
end
