# This file was generated by GoReleaser. DO NOT EDIT.
cask "gh-repo-dashboard" do
  version "1.4.0"

  on_macos do
    on_intel do
      sha256 "bc13fa4d5bcfe786c836eeda466526cce585f5499c1e97d0a0d21ad1b01a84ed"
      url "https://github.com/KyleKing/gh-repo-dashboard/releases/download/v#{version}/gh-repo-dashboard-darwin-amd64"
      binary "gh-repo-dashboard-darwin-amd64", target: "gh-repo-dashboard"
    end
    on_arm do
      sha256 "ed510a5fbe2f3d974c9693b7e8498663db07d9937ff06baa4e5190a805d327d1"
      url "https://github.com/KyleKing/gh-repo-dashboard/releases/download/v#{version}/gh-repo-dashboard-darwin-arm64"
      binary "gh-repo-dashboard-darwin-arm64", target: "gh-repo-dashboard"
    end
  end

  on_linux do
    on_intel do
      sha256 "61ece6bccbd8eed8b33da180791f1882c3968aef7ba3a9ab09de087bc744f1f9"
      url "https://github.com/KyleKing/gh-repo-dashboard/releases/download/v#{version}/gh-repo-dashboard-linux-amd64"
      binary "gh-repo-dashboard-linux-amd64", target: "gh-repo-dashboard"
    end
    on_arm do
      sha256 "29ad8629fc58469309c332db34b6506f4850e934126c11525012768b0e85f2d9"
      url "https://github.com/KyleKing/gh-repo-dashboard/releases/download/v#{version}/gh-repo-dashboard-linux-arm64"
      binary "gh-repo-dashboard-linux-arm64", target: "gh-repo-dashboard"
    end
  end

  name "gh-repo-dashboard"
  desc "K9s-inspired Bubble Tea TUI for managing multiple git and jj repositories"
  homepage "https://github.com/kyleking/gh-repo-dashboard"

  livecheck do
    skip "Auto-generated on release."
  end

  postflight do
    Dir.glob(File.join(staged_path, "gh-repo-dashboard*")).each do |f|
      system_command "/usr/bin/xattr", args: ["-c", f], must_succeed: false
    end
  end

  # No zap stanza required

end
