# This file was generated by GoReleaser. DO NOT EDIT.
cask "gh-repo-dashboard" do
  version "1.6.0"

  on_macos do
    on_intel do
      sha256 "038288dbb45cb7e10434c5344a1f878a39e68a17951d83431ee3b97dd2bea778"
      url "https://github.com/KyleKing/gh-repo-dashboard/releases/download/v#{version}/gh-repo-dashboard-darwin-amd64"
      binary "gh-repo-dashboard-darwin-amd64", target: "gh-repo-dashboard"
    end
    on_arm do
      sha256 "220b2042d306e01f9ecebba527d518d35879ba1c29498f11b90c66ef42d95de1"
      url "https://github.com/KyleKing/gh-repo-dashboard/releases/download/v#{version}/gh-repo-dashboard-darwin-arm64"
      binary "gh-repo-dashboard-darwin-arm64", target: "gh-repo-dashboard"
    end
  end

  on_linux do
    on_intel do
      sha256 "2cadbdee65b30e87bea1524c113e4e66ddaf09bdbcb30d160953140d1a39b3b7"
      url "https://github.com/KyleKing/gh-repo-dashboard/releases/download/v#{version}/gh-repo-dashboard-linux-amd64"
      binary "gh-repo-dashboard-linux-amd64", target: "gh-repo-dashboard"
    end
    on_arm do
      sha256 "23e2ab2e62aa3d65964e1b0a9808a14760e52673e8ecf6705326e61411ef113c"
      url "https://github.com/KyleKing/gh-repo-dashboard/releases/download/v#{version}/gh-repo-dashboard-linux-arm64"
      binary "gh-repo-dashboard-linux-arm64", target: "gh-repo-dashboard"
    end
  end

  name "gh-repo-dashboard"
  desc "K9s-inspired Bubble Tea TUI for managing multiple git and jj repositories"
  homepage "https://github.com/kyleking/gh-repo-dashboard"

  livecheck do
    skip "Auto-generated on release."
  end

  postflight do
    Dir.glob(File.join(staged_path, "gh-repo-dashboard*")).each do |f|
      system_command "/usr/bin/xattr", args: ["-c", f], must_succeed: false
    end
  end

  # No zap stanza required

end
