# This file was generated by GoReleaser. DO NOT EDIT.
cask "gh-sweep" do
  version "0.10.0"

  on_macos do
    on_arm do
      sha256 "db80718ac820ec861b4c6c3364a9d909a4172cfc08d41185434a7dde25829ac6"
      url "https://github.com/KyleKing/gh-sweep/releases/download/v#{version}/gh-sweep-darwin-arm64"
      binary "gh-sweep-darwin-arm64", target: "gh-sweep"
    end
    on_intel do
      sha256 "74f78b8a052f7f7f8b88ce331bbe6d1cd1c01cad8243ad1ae93a3a7208f75128"
      url "https://github.com/KyleKing/gh-sweep/releases/download/v#{version}/gh-sweep-darwin-amd64"
      binary "gh-sweep-darwin-amd64", target: "gh-sweep"
    end
  end
  on_linux do
    on_arm do
      sha256 "ca960086a5a583aa9e44a89e582fa16c6915ff0ca2a70bc8f6e92389cac39e89"
      url "https://github.com/KyleKing/gh-sweep/releases/download/v#{version}/gh-sweep-linux-arm64"
      binary "gh-sweep-linux-arm64", target: "gh-sweep"
    end
    on_intel do
      sha256 "c7248759c1c20984efeb66b7f979dd83d35f91f2e128b7260a86fd949320b2c7"
      url "https://github.com/KyleKing/gh-sweep/releases/download/v#{version}/gh-sweep-linux-amd64"
      binary "gh-sweep-linux-amd64", target: "gh-sweep"
    end
  end

  name "gh-sweep"
  desc "TUI for sweeping GitHub repositories: dead branches, unresolved review threads, protection drift, and slow workflows."
  homepage "https://github.com/KyleKing/gh-sweep"

  livecheck do
    skip "Auto-generated on release."
  end

  postflight do
    Dir.glob(File.join(staged_path, "gh-sweep*")).each do |f|
      system_command "/usr/bin/xattr", args: ["-c", f], must_succeed: false
    end
  end

  # No zap stanza required
end
