# This file was generated by GoReleaser. DO NOT EDIT.
cask "gh-sweep" do
  version "1.0.0"

  on_macos do
    on_arm do
      sha256 "ff20214d64d9be582c27b1e6c9c4eda661e4230a11ab9ccbf217f11471e4bccf"
      url "https://github.com/KyleKing/gh-sweep/releases/download/v#{version}/gh-sweep-darwin-arm64"
      binary "gh-sweep-darwin-arm64", target: "gh-sweep"
    end
    on_intel do
      sha256 "cc56beff93130c4adb9c1678f5fc8832e2f46f6b196531b3e2bc71209ffa3bfa"
      url "https://github.com/KyleKing/gh-sweep/releases/download/v#{version}/gh-sweep-darwin-amd64"
      binary "gh-sweep-darwin-amd64", target: "gh-sweep"
    end
  end
  on_linux do
    on_arm do
      sha256 "b01b2b9d16793249965bfd987721cb0255dc608434810731b232a5a84a34288d"
      url "https://github.com/KyleKing/gh-sweep/releases/download/v#{version}/gh-sweep-linux-arm64"
      binary "gh-sweep-linux-arm64", target: "gh-sweep"
    end
    on_intel do
      sha256 "9d0a027729148455db0736eb2b54df0f3b1991036c62d7db3e050a79b7998e6d"
      url "https://github.com/KyleKing/gh-sweep/releases/download/v#{version}/gh-sweep-linux-amd64"
      binary "gh-sweep-linux-amd64", target: "gh-sweep"
    end
  end

  name "gh-sweep"
  desc "TUI for sweeping GitHub repositories: dead branches, unresolved review threads, protection drift, and slow workflows."
  homepage "https://github.com/KyleKing/gh-sweep"

  livecheck do
    skip "Auto-generated on release."
  end

  postflight do
    Dir.glob(File.join(staged_path, "gh-sweep*")).each do |f|
      system_command "/usr/bin/xattr", args: ["-c", f], must_succeed: false
    end
  end

  # No zap stanza required
end
