# This file was generated by GoReleaser. DO NOT EDIT.
cask "gh-star-search" do
  version "1.0.7"

  on_macos do
    on_arm do
      sha256 "3f63764221ef10ec13c5c627fdbd521c8e10717a6135009f0d004df55e14f9e5"
      url "https://github.com/KyleKing/gh-star-search/releases/download/v#{version}/gh-star-search-darwin-arm64"
      binary "gh-star-search-darwin-arm64", target: "gh-star-search"
    end
    on_intel do
      sha256 "d53bba86efcdbc3b35ec6c03a28efc5e115f68e202e00b72d85bb43485406b73"
      url "https://github.com/KyleKing/gh-star-search/releases/download/v#{version}/gh-star-search-darwin-amd64"
      binary "gh-star-search-darwin-amd64", target: "gh-star-search"
    end
  end

  name "gh-star-search"
  desc "GH CLI extension to search your stars "
  homepage "https://github.com/KyleKing/gh-star-search"

  livecheck do
    skip "Auto-generated on release."
  end

  postflight do
    Dir.glob(File.join(staged_path, "gh-star-search*")).each do |f|
      system_command "/usr/bin/xattr", args: ["-c", f], must_succeed: false
    end
  end

  # No zap stanza required
end
