# This file was generated by GoReleaser. DO NOT EDIT.
cask "gh-sweep" do
  version "0.9.1"

  on_macos do
    on_arm do
      sha256 "f657e944fcc0d254efce931917fec44a7e5103274e8d6e9d37c63b37cbb450db"
      url "https://github.com/KyleKing/gh-sweep/releases/download/v#{version}/gh-sweep-darwin-arm64"
      binary "gh-sweep-darwin-arm64", target: "gh-sweep"
    end
    on_intel do
      sha256 "1ae896f10c269e6118dab3835d0731de787c2f2bae4315553b715244c155b2ee"
      url "https://github.com/KyleKing/gh-sweep/releases/download/v#{version}/gh-sweep-darwin-amd64"
      binary "gh-sweep-darwin-amd64", target: "gh-sweep"
    end
  end
  on_linux do
    on_arm do
      sha256 "5ff268659dfc531d865b7e85b4f1bf6072507c4d22b586b5bbcf0d01d707c5e3"
      url "https://github.com/KyleKing/gh-sweep/releases/download/v#{version}/gh-sweep-linux-arm64"
      binary "gh-sweep-linux-arm64", target: "gh-sweep"
    end
    on_intel do
      sha256 "c6f0bf64db4ce156668a66b16a33f21eac8167983eb7f1d38aaf50b386dd1146"
      url "https://github.com/KyleKing/gh-sweep/releases/download/v#{version}/gh-sweep-linux-amd64"
      binary "gh-sweep-linux-amd64", target: "gh-sweep"
    end
  end

  name "gh-sweep"
  desc "TUI for sweeping GitHub repositories: dead branches, unresolved review threads, protection drift, and slow workflows."
  homepage "https://github.com/KyleKing/gh-sweep"

  livecheck do
    skip "Auto-generated on release."
  end

  postflight do
    Dir.glob(File.join(staged_path, "gh-sweep*")).each do |f|
      system_command "/usr/bin/xattr", args: ["-c", f], must_succeed: false
    end
  end

  # No zap stanza required
end
