# This file was generated by GoReleaser. DO NOT EDIT.
cask "gh-star-search" do
  version "1.0.5"

  on_macos do
    on_intel do
      sha256 "f0805603191dbbe277a7df4e684218518ab913bf8ec8e59722a632542f041af8"
      url "https://github.com/KyleKing/gh-star-search/releases/download/v#{version}/gh-star-search-darwin-amd64"
      binary "gh-star-search-darwin-amd64", target: "gh-star-search"
    end
    on_arm do
      sha256 "139e9d031bc59200c628ae525f3f82dcbae6b7c98ebbc791ede541523fa61cee"
      url "https://github.com/KyleKing/gh-star-search/releases/download/v#{version}/gh-star-search-darwin-arm64"
      binary "gh-star-search-darwin-arm64", target: "gh-star-search"
    end
  end

  name "gh-star-search"
  desc "GH CLI extension to search your stars "
  homepage "https://github.com/KyleKing/gh-star-search"

  livecheck do
    skip "Auto-generated on release."
  end

  postflight do
    Dir.glob(File.join(staged_path, "gh-star-search*")).each do |f|
      system_command "/usr/bin/xattr", args: ["-c", f], must_succeed: false
    end
  end

  # No zap stanza required

end
