# This file was generated by GoReleaser. DO NOT EDIT.
cask "gh-star-search" do
  version "1.0.9"

  on_macos do
    on_arm do
      sha256 "644cc0f4e62d85a3245366added87426fefb406018d3ab1a6b6fbc3c8e656136"
      url "https://github.com/KyleKing/gh-star-search/releases/download/v#{version}/gh-star-search-darwin-arm64"
      binary "gh-star-search-darwin-arm64", target: "gh-star-search"
    end
    on_intel do
      sha256 "cedb80596c6e725cf85247a7c8aae08e29df7f53e34ebcaf4ae5b89c17ccc269"
      url "https://github.com/KyleKing/gh-star-search/releases/download/v#{version}/gh-star-search-darwin-amd64"
      binary "gh-star-search-darwin-amd64", target: "gh-star-search"
    end
  end

  name "gh-star-search"
  desc "GH CLI extension to search your stars "
  homepage "https://github.com/KyleKing/gh-star-search"

  livecheck do
    skip "Auto-generated on release."
  end

  postflight do
    Dir.glob(File.join(staged_path, "gh-star-search*")).each do |f|
      system_command "/usr/bin/xattr", args: ["-c", f], must_succeed: false
    end
  end

  # No zap stanza required
end
