# This file was generated by GoReleaser. DO NOT EDIT.
cask "jj-diff" do
  version "0.2.0"

  on_macos do
    on_arm do
      sha256 "2c4ae0c05eb149827b7be6c58b445a3cbfa05b6ad543e9d4be90b8ff169c392b"
      url "https://github.com/KyleKing/jj-diff/releases/download/v#{version}/jj-diff-darwin-arm64"
      binary "jj-diff-darwin-arm64", target: "jj-diff"
    end
    on_intel do
      sha256 "dd0bacd20279d7632ac77cdf5fcbd62eaf0e2176cb8b799aef088c6255c2219e"
      url "https://github.com/KyleKing/jj-diff/releases/download/v#{version}/jj-diff-darwin-amd64"
      binary "jj-diff-darwin-amd64", target: "jj-diff"
    end
  end
  on_linux do
    on_arm do
      sha256 "da9ff0f50ef05296b9c26ab626fb76e9f7e16091f610edb25f8182ff874a4f1c"
      url "https://github.com/KyleKing/jj-diff/releases/download/v#{version}/jj-diff-linux-arm64"
      binary "jj-diff-linux-arm64", target: "jj-diff"
    end
    on_intel do
      sha256 "fd77cded1135a284efcf889f36681edf76d686b04d53e1a899c067fe1b4565da"
      url "https://github.com/KyleKing/jj-diff/releases/download/v#{version}/jj-diff-linux-amd64"
      binary "jj-diff-linux-amd64", target: "jj-diff"
    end
  end

  name "jj-diff"
  desc "Exploring better diff management for jj"
  homepage "https://github.com/kyleking/jj-diff"

  livecheck do
    skip "Auto-generated on release."
  end

  postflight do
    Dir.glob(File.join(staged_path, "jj-diff*")).each do |f|
      system_command "/usr/bin/xattr", args: ["-c", f], must_succeed: false
    end
  end

  # No zap stanza required
end
