# This file was generated by GoReleaser. DO NOT EDIT.
cask "jj-diff" do
  version "0.1.5"

  on_macos do
    on_intel do
      sha256 "bda6752d51b3282e176ce4822bc28027724de9face5917f073c12b87c586ef72"
      url "https://github.com/KyleKing/jj-diff/releases/download/v#{version}/jj-diff-darwin-amd64"
      binary "jj-diff-darwin-amd64", target: "jj-diff"
    end
    on_arm do
      sha256 "3925dd56c490a38b8a8146b7e68eb6390ba8db2eab27664051a4466aefa3262f"
      url "https://github.com/KyleKing/jj-diff/releases/download/v#{version}/jj-diff-darwin-arm64"
      binary "jj-diff-darwin-arm64", target: "jj-diff"
    end
  end

  on_linux do
    on_intel do
      sha256 "44e136b48d24fabf851d02eb3baf88779f988833e01c03c5e25355a0e66b9c68"
      url "https://github.com/KyleKing/jj-diff/releases/download/v#{version}/jj-diff-linux-amd64"
      binary "jj-diff-linux-amd64", target: "jj-diff"
    end
    on_arm do
      sha256 "d79a5f80d2c5e2ac929ea2fac186bbc268ac70d5771805f53626c76f07f77aa1"
      url "https://github.com/KyleKing/jj-diff/releases/download/v#{version}/jj-diff-linux-arm64"
      binary "jj-diff-linux-arm64", target: "jj-diff"
    end
  end

  name "jj-diff"
  desc "Exploring better diff management for jj"
  homepage "https://github.com/kyleking/jj-diff"

  livecheck do
    skip "Auto-generated on release."
  end

  postflight do
    Dir.glob(File.join(staged_path, "jj-diff*")).each do |f|
      system_command "/usr/bin/xattr", args: ["-c", f], must_succeed: false
    end
  end

  # No zap stanza required

end
