# This file was generated by GoReleaser. DO NOT EDIT.
cask "jj-diff" do
  version "0.3.0"

  on_macos do
    on_arm do
      sha256 "d03be60dcaadbd2d953a7a5a86ff0f6fb44c40c8792c9ea705bf0a0cf384c2c8"
      url "https://github.com/KyleKing/jj-diff/releases/download/v#{version}/jj-diff-darwin-arm64"
      binary "jj-diff-darwin-arm64", target: "jj-diff"
    end
    on_intel do
      sha256 "604b528ba5ab9db7a68e8dcdb10807bdc4815b1fbfab2b2285cdca90a061f214"
      url "https://github.com/KyleKing/jj-diff/releases/download/v#{version}/jj-diff-darwin-amd64"
      binary "jj-diff-darwin-amd64", target: "jj-diff"
    end
  end
  on_linux do
    on_arm do
      sha256 "03e4cb15efbb9031296cca72faf31fee0118855295464bbe0c1d4a59a006fe64"
      url "https://github.com/KyleKing/jj-diff/releases/download/v#{version}/jj-diff-linux-arm64"
      binary "jj-diff-linux-arm64", target: "jj-diff"
    end
    on_intel do
      sha256 "2c772dff7cf904e4655634146eb52adee18356ffac2bf51c8481ae6df664efd3"
      url "https://github.com/KyleKing/jj-diff/releases/download/v#{version}/jj-diff-linux-amd64"
      binary "jj-diff-linux-amd64", target: "jj-diff"
    end
  end

  name "jj-diff"
  desc "Exploring better diff management for jj"
  homepage "https://github.com/kyleking/jj-diff"

  livecheck do
    skip "Auto-generated on release."
  end

  postflight do
    Dir.glob(File.join(staged_path, "jj-diff*")).each do |f|
      system_command "/usr/bin/xattr", args: ["-c", f], must_succeed: false
    end
  end

  # No zap stanza required
end
