# This file was generated by GoReleaser. DO NOT EDIT.
cask "second-look" do
  version "0.12.0"

  on_macos do
    on_arm do
      sha256 "af437cc6e865a320ac24d1479fe3484abbd24647e83804da176ae844b032946a"
      url "https://github.com/KyleKing/second-look/releases/download/v#{version}/second-look-darwin-arm64"
      binary "second-look-darwin-arm64", target: "second-look"
    end
    on_intel do
      sha256 "00e32666aa746986b60dec9d0a1135a2dd5fb727ec703ad5ddfeffa538fff40e"
      url "https://github.com/KyleKing/second-look/releases/download/v#{version}/second-look-darwin-amd64"
      binary "second-look-darwin-amd64", target: "second-look"
    end
  end
  on_linux do
    on_arm do
      sha256 "e1a792e97ae86204ce1e6af7a91293c0a845af6b6c4cbd823aa015ddae1b6328"
      url "https://github.com/KyleKing/second-look/releases/download/v#{version}/second-look-linux-arm64"
      binary "second-look-linux-arm64", target: "second-look"
    end
    on_intel do
      sha256 "f5825967db8b5cf76d6420c733c04d42b7376ff3b2a88637480049734497d099"
      url "https://github.com/KyleKing/second-look/releases/download/v#{version}/second-look-linux-amd64"
      binary "second-look-linux-amd64", target: "second-look"
    end
  end

  name "second-look"
  desc "Prepare a code review locally, then post it to GitHub in one deterministic call"
  homepage "https://github.com/kyleking/second-look"

  livecheck do
    skip "Auto-generated on release."
  end

  postflight do
    Dir.glob(File.join(staged_path, "second-look*")).each do |f|
      system_command "/usr/bin/xattr", args: ["-c", f], must_succeed: false
    end
  end

  # No zap stanza required
end
