# This file was generated by GoReleaser. DO NOT EDIT.
cask "second-look" do
  version "0.24.0"

  on_macos do
    on_arm do
      sha256 "ddd04b3a877f213bcd087fc92669ccdf64775ef194fa0082a37f3f955636c833"
      url "https://github.com/KyleKing/second-look/releases/download/v#{version}/second-look-darwin-arm64"
      binary "second-look-darwin-arm64", target: "second-look"
    end
    on_intel do
      sha256 "15a0c65870a797314f6a3662917582663fe43554be2c2e50c7c2eb5f1cf150ed"
      url "https://github.com/KyleKing/second-look/releases/download/v#{version}/second-look-darwin-amd64"
      binary "second-look-darwin-amd64", target: "second-look"
    end
  end
  on_linux do
    on_arm do
      sha256 "e52f585266b62f93dab89ebb9f16be166afc10cfe7a05aaeecf7b6481da2a005"
      url "https://github.com/KyleKing/second-look/releases/download/v#{version}/second-look-linux-arm64"
      binary "second-look-linux-arm64", target: "second-look"
    end
    on_intel do
      sha256 "cb1c429eac6c639ac0bba266236a5914a2bee2898dd52ec4fe52b8014240be23"
      url "https://github.com/KyleKing/second-look/releases/download/v#{version}/second-look-linux-amd64"
      binary "second-look-linux-amd64", target: "second-look"
    end
  end

  name "second-look"
  desc "Prepare a code review locally, then post it to GitHub in one deterministic call"
  homepage "https://github.com/kyleking/second-look"

  livecheck do
    skip "Auto-generated on release."
  end

  postflight do
    Dir.glob(File.join(staged_path, "second-look*")).each do |f|
      system_command "/usr/bin/xattr", args: ["-c", f], must_succeed: false
    end
  end

  # No zap stanza required
end
