# This file was generated by GoReleaser. DO NOT EDIT.
cask "second-look" do
  version "0.7.0"

  on_macos do
    on_arm do
      sha256 "7f765288681d338ea761718fa7f7cb3b7352be7c0f3ea1a0eae602b56050b3bb"
      url "https://github.com/KyleKing/second-look/releases/download/v#{version}/second-look-darwin-arm64"
      binary "second-look-darwin-arm64", target: "second-look"
    end
    on_intel do
      sha256 "fe8e43123b7cbb74f0bd4337138aea8d0f2bd231facea75dd624780aee0b36ce"
      url "https://github.com/KyleKing/second-look/releases/download/v#{version}/second-look-darwin-amd64"
      binary "second-look-darwin-amd64", target: "second-look"
    end
  end
  on_linux do
    on_arm do
      sha256 "c400ff41f90c01b9a60a222b266aca3ebc0ba49a3ca03be41f0106e3907f7dea"
      url "https://github.com/KyleKing/second-look/releases/download/v#{version}/second-look-linux-arm64"
      binary "second-look-linux-arm64", target: "second-look"
    end
    on_intel do
      sha256 "2c37f231da9f4fb418795a7184f0e41240a9a59e7f9d7bc48fc506e63871b0bc"
      url "https://github.com/KyleKing/second-look/releases/download/v#{version}/second-look-linux-amd64"
      binary "second-look-linux-amd64", target: "second-look"
    end
  end

  name "second-look"
  desc "Prepare a code review locally, then post it to GitHub in one deterministic call"
  homepage "https://github.com/kyleking/second-look"

  livecheck do
    skip "Auto-generated on release."
  end

  postflight do
    Dir.glob(File.join(staged_path, "second-look*")).each do |f|
      system_command "/usr/bin/xattr", args: ["-c", f], must_succeed: false
    end
  end

  # No zap stanza required
end
