# This file was generated by GoReleaser. DO NOT EDIT.
cask "wavez" do
  version "0.20.0"

  on_macos do
    on_arm do
      sha256 "9df1beee21d686a13c7933ef0ceb3b589f8d8c2911574f8d95be3af0d7859222"
      url "https://github.com/KyleKing/wavez/releases/download/v#{version}/wavez-darwin-arm64.tar.gz"
    end
    on_intel do
      sha256 "57cc05645580dae8973a3ea5f87a79a049a524c86fe3d3bffbf7dade1ce78782"
      url "https://github.com/KyleKing/wavez/releases/download/v#{version}/wavez-darwin-amd64.tar.gz"
    end
  end

  name "wavez"
  desc "A personal AI coding agent for one user, one laptop, and repeated narrow work"
  homepage "https://github.com/kyleking/wavez"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "wavez"

  postflight do
    Dir.glob(File.join(staged_path, "wavez*")).each do |f|
      system_command "/usr/bin/xattr", args: ["-c", f], must_succeed: false
    end
  end

  # No zap stanza required
end
