# This file was generated by GoReleaser. DO NOT EDIT.
cask "wavez" do
  version "0.17.0"

  on_macos do
    on_arm do
      sha256 "cd3fdf5987e1074ceaade7d05a6df1f9855d07eff3b7028276775bf061610fd9"
      url "https://github.com/KyleKing/wavez/releases/download/v#{version}/wavez-darwin-arm64.tar.gz"
    end
    on_intel do
      sha256 "1aa03d39ce73ca01e0d3b325ec5a85545cdf26f49d057bdc0b920c539e09e4b8"
      url "https://github.com/KyleKing/wavez/releases/download/v#{version}/wavez-darwin-amd64.tar.gz"
    end
  end

  name "wavez"
  desc "A personal AI coding agent for one user, one laptop, and repeated narrow work"
  homepage "https://github.com/kyleking/wavez"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "wavez"

  postflight do
    Dir.glob(File.join(staged_path, "wavez*")).each do |f|
      system_command "/usr/bin/xattr", args: ["-c", f], must_succeed: false
    end
  end

  # No zap stanza required
end
