# This file was generated by GoReleaser. DO NOT EDIT.
cask "wavez" do
  version "0.21.0"

  on_macos do
    on_arm do
      sha256 "8cb18fc0dacfa7c2a44f26f178c25603e554e1474eeb0b364feb50f3ebe7d381"
      url "https://github.com/KyleKing/wavez/releases/download/v#{version}/wavez-darwin-arm64.tar.gz"
    end
    on_intel do
      sha256 "0dbfd60857c961427aead264f0b841ae04a37426bb2be28926dafa7cae2bce16"
      url "https://github.com/KyleKing/wavez/releases/download/v#{version}/wavez-darwin-amd64.tar.gz"
    end
  end

  name "wavez"
  desc "A personal AI coding agent for one user, one laptop, and repeated narrow work"
  homepage "https://github.com/kyleking/wavez"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "wavez"

  postflight do
    Dir.glob(File.join(staged_path, "wavez*")).each do |f|
      system_command "/usr/bin/xattr", args: ["-c", f], must_succeed: false
    end
  end

  # No zap stanza required
end
